spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/loja
    username: root
    password: 

  jpa:
    hibernate: 
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  mail:
    host: smtp.gmail.com
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          ssl:
            enable: true