spring: 
  datasource: 
    url: mysql://be8132e6df3d19:c76596b6@us-cdbr-east-02.cleardb.com/heroku_b402378915be2b2?reconnect=true
    username: root
    password: 

  jpa:
    hibernate: 
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
  mail:
      host: smtp.gmail.com
      username: 
      password: 
      properties:
        mail:
          smtp:
            auth: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
              fallback: false
            starttls:
              enable: true
            ssl:
              enable: true